### PR TITLE
Asynchronously load note embeds

### PR DESCRIPTION
**Pull request by reefdog**
The note embed code looks like this:

``` html
<div id="DC-note-1234" class="DC-note-container"></div>
<script src="//assets.documentcloud.org/notes/loader.js"></script>
<script>
  dc.embed.loadNote('//www.documentcloud.org/documents/4567-doc-title/annotations/1234.json');
</script>
```

It depends on render-blocking syncronous script loading:
1. `loader.js` loads remotely (blocking)
2. `loader.js` uses `document.write` to add `note_embed.js` to the DOM (bad practice and being deprecated)
3. `note_embed.js` loads remotely (blocking)
4. `dc.embed.loadNote` called via inline script

For backwards compatibility with existing embed codes, we're stuck with 1 and 4, but we can fix 2 and 3.
### After this PR is merged:
- `loader.js` redefines `dc.embed.loadNote` as a queuing function
- `loader.js` uses `document.createElement` (instead of `document.write`) to add `note_embed.js` to the DOM
  - and is smart enough to only add it if necessary
  - and adds it with the `async` attribute so page rendering can continue
- When `note_embed.js` finishes loading, queued notes are loaded
- If `note_embed.js` has already run when `loader.js` does (like in pjax page changes where both from/to pages contain note embeds) the note loads immediately instead of being queued

There's also the addition of container-less note embeds at invocation site, because (1) I thought it was existing functionality that I'd broken and (2) @knowtheory accidentally challenged me to do it. So this is now a supported – if slow and discouraged – embed code:

``` html
<script src="//assets.documentcloud.org/notes/loader.js"></script>
<script>
  dc.embed.loadNote('//www.documentcloud.org/documents/4567-doc-title/annotations/1234.json');
</script>
```

One downside: we now require IE8+. `loader.js` (which doesn't include jQuery) uses `document.querySelector` to avoid redundant DOM insertions of `note_embed.css` and `note_embed.js`. If that's a problem, I can tweak it so that only supported browsers avoid redundant insertions, and older browsers get the existing behavior.

### CODE REVIEW

**Comment by knowtheory** [comment]
This is awesommmmme.

Nah, screw IE8.  We can pull numbers if we need to but looking at Google analytics, IEs <10 have dwindled sufficiently.

**Comment by knowtheory** [comment]
Now, loader.js w/ document.write causes problems when dynamically inserted (for example in the case of pjax pages).  Does loader.js w/ createElement/appendChild suffer the same problem?

**Comment by reefdog** [comment]
> Now, loader.js w/ document.write causes problems when dynamically inserted (for example in the case of pjax pages). Does loader.js w/ createElement/appendChild suffer the same problem?

Yes, but for a different reason. Given the script order in our existing vended embed codes:

1. `<script src="loader.js"></script>`
2. `<script>dc.embed.loadNote()</script>`

What we ✅  are able to do: change `loader.js` so that `dc.embed.loadNote()` becomes a queueing function, writes `note_embed.js` with `createElement` instead of `document.write`, and loads notes asynchronously.

What we ❌  aren't able to do: survive anything that causes the inline script `dc.embed.loadNote()` to fire before `loader.js` has loaded.

Unfortunately, what I've discovered:

1. Pjax removes `<script src>` tags from the content and inserts them into `<head>`, which breaks the gaurantee that they'll load and execute synchronously before the inline script tags. This is [by design](https://github.com/defunkt/jquery-pjax/issues/331#issuecomment-54364324) and [unlikely to change](https://github.com/defunkt/jquery-pjax/issues/502#issuecomment-78863091).
2. jQuery seems to do something similar, but I haven't nailed down its behavior precisely. In any case, fetching a vanilla note embed code with `$.get()` and inserting it onto page with `.html()` causes the inline script to be executed before `loader.js` has loaded/executed.

So effectively: people who use Pjax (or otherwise pull in content via Ajax) who really want to embed our notes will need to add our `<script src="loader.js"></script>` to their templates to make sure the loader is present on every page before the content is fetched/inserted.

**Comment by reefdog** [comment]
Happy enough with this to merge, make necessary platform changes, and deploy. Passes browser testing and there're no regressions I can find. It doesn't magically make our existing embed codes work in pjax-y environments, but now we know why.

@knowtheory do you need to take a look at this, or can I merge (once I've made the necessary changes to the platform too)?

**Pull request merged**
